### PR TITLE
Refactor sclang.vim as a lua module

### LINKED ISSUE #88: Rewrite sclang.vim as a lua module

### LINKED ISSUE #119: Incomplete lines in post window output
`.trace` and similar give inconsistent results where at times only one parameter is seen, sometimes with, sometimes without it's value and sometimes just as the first character of that message.

I thought that `.trace` and similar diagnostic tools would be able to show it's data reliably in the post window.

Run this code in scnvim to reproduce the error:
```
(
Pbind(
    \freq, Pwhite(100,500), 
    \dur, Prand([0.15, 0.25, 0.3], inf),
    \amp, 0.2,
    \legato, 0.3,
).trace.play;
)
```

Here is some sample output from my post window from when I ran the above code:
```
( 'legato': 0.3, 'dur': 0.15, 'amp': 0.2, 'freq': 271 )
( 'legato': 0.3
( 'legato': 0.3, 'dur': 0.3, 'amp': 0.2, 'freq': 340 )
( 'legato': 
( 'legato': 0.3, 'dur': 0.15, 'amp': 0.2, 'freq': 247 )
( 'legato': 0.3
( 'legato': 0.3, 'dur': 0.3, 'amp': 0.2, 'freq': 374 )
( 'legato': 0.3
( 'legato': 0.3, 'dur': 0.25, 'amp': 0.2, 'freq': 215 )
( 'legato': 
( 'legato': 0.3, 'dur': 0.15, 'amp': 0.2, 'freq': 169 )
( 'legato': 0.3
( 'legato': 0.3, 'dur': 0.3, 'amp': 0.2, 'freq': 163 )
( 'legato': 0.3
( 'legato': 0.3, 'dur': 0.3, 'amp': 0.2, 'freq': 382 )
( 
( 'legato': 0.3, 'dur': 0.3, 'amp': 0.2, 'freq': 166 )
( 'legato': 0.3
( 'legato': 0.3, 'dur': 0.25, 'amp': 0.2, 'freq': 294 )
( 'legato': 0.3
( 'legato': 0.3, 'dur': 0.25, 'amp': 0.2, 'freq': 177 )
( 'legato': 0.3
```

NVIM v0.4.3
Mac OS X 10.12.6
Running scnvim in Kitty

### LINKED ISSUE #123: Excessive CPU usage with MIDI trace
**Describe the bug**
Using ~70% CPU on a dual core i7 from just tracing incoming MIDI.

**Expected behavior**
Way less CPU usage.

**Steps to reproduce**
1. Connect some MIDI device capable of sending CC.
2. `MIDIIn.connectAll;`
3. `MIDIFunc.trace(true)`
4. Send CC values. Quickly. Fast.
5. open your favorite `top` and monitor blame

**Additional context**
Not sure if this is a bug in SuperCollider on Linux or if it is `nvim` that gets overthrown by the amount of lines it needs to create in the `SCNVIM` split.

**Information**
- `nvim --version`: NVIM v0.5.0-782-gb6897ebc0
- Operating system: Arch Linux
- Kernel: 5.9.1-rt20-1-rt
- Running scnvim in a Terminal/GUI: Alacritty

### PR DESCRIPTION
**Pull request by davidgranstrom**
Close #119 
Close #88 
Close #123 

TODO

- [x] Test on windows
- [x] Test with nvim 0.4.4
- [x] Increase minimum required nvim version to 0.4.4 in docs

### CODE REVIEW

**Comment by davidgranstrom** [comment]
I think this is ready now. I will use this as my daily driver for now until its been merged just to see if there are any issues. I would be very grateful for any feedback on this PR if anyone tries it out!

@salkin-mada  CPU usage is now on-par with ScIDE (at least on my system). 
I've used this snippet for testing `Pbind(\degree, Pseq((0..9), inf), \dur, 1/512).trace.play;`. I have thought about some more optimizations as well, but I think that will have to wait until I port `postwindow.vim` completely to lua :)

@danielmkarlsson This PR also fixes the long standing issue with broken lines in the post window output.

cc: @madskjeldgaard @kflak

**Comment by madskjeldgaard** [comment]
Beautiful. can't wait to try this out!

**Comment by davidgranstrom** [comment]
I have also exposed some new API functions that proved to be quite fun. It is now possible to override the following functions:

```lua
--- Function to run on sclang start
M.on_start = function() end

--- Function to run on sclang exit
--@param code The exit code
--@param signal The Signal
M.on_exit = function(code, signal) end

--- Function to run on sclang output
--@param line sclang post window output
M.on_read = function(line) end
```

I did a test using a custom floating style sclang post window (I might add this as an option to scnvim even..), you can check out the implementation [here!](https://github.com/davidgranstrom/vim-conf/blob/master/lua/dkg/supercollider.lua)

Screenshot 2020-11-14 at 14 31 38

**Comment by davidgranstrom** [comment]
I've still not decided if `on_read` is a good handler name.. might rename it to `on_post`, `on_print` or `on_output` just to give you a heads up. Any input on this is appreciated!

**Comment by madskjeldgaard** [comment]
> I have also exposed some new API functions that proved to be quite fun. It is now possible to override the following functions:
> 
> ```lua
> --- Function to run on sclang start
> M.on_start = function() end
> 
> --- Function to run on sclang exit
> --@param code The exit code
> --@param signal The Signal
> M.on_exit = function(code, signal) end
> 
> --- Function to run on sclang output
> --@param line sclang post window output
> M.on_read = function(line) end
> ```
> 
> I did a test using a custom floating style sclang post window (I might add this as an option to scnvim even..), you can check out the implementation [here!](https://github.com/davidgranstrom/vim-conf/blob/master/lua/dkg/supercollider.lua)
> 
> Screenshot 2020-11-14 at 14 31 38

wowowowowow ! Switching to this branch now and will test / hack it !

**Comment by salkin-mada** [comment]
@davidgranstrom fantastic!

**Comment by madskjeldgaard** [comment]
I'm not sure if it's related to this PR or an error that's been there all along in the syntax highlighting for the post window (probably the latter) but reopening the postwindow seems to screw up smoe of the highlighting. 

Notice how the return value changes color below 

errorsyntax

I'll have a closer look at this later

**Comment by madskjeldgaard** [comment]
> I'm not sure if it's related to this PR or an error that's been there all along in the syntax highlighting for the post window (probably the latter) but reopening the postwindow seems to screw up smoe of the highlighting.
> 
> Notice how the return value changes color below
> 
> errorsyntax
> 
> I'll have a closer look at this later

ah this is definately an edge case problem from my PR. Nevermind

**Comment by salkin-mada** [comment]
> I've still not decided if `on_read` is a good handler name.. might rename it to `on_post`, `on_print` or `on_output` just to give you a heads up. Any input on this is appreciated!

I would agree that `on_post` is better than `on_read`

Also I think a floaty post window option would be very nice. it goes well together with the floaty window possibilities of lua snippets. I have a local branch running here which supports `:SCNvimTags` creating lua style snippets and which offers `scnvim` support of `snippets.nvim` in addition til `UltiSnips`

scrn-2020-11-14-04-15-03
scrn-2020-11-14-04-15-53

**Comment by salkin-mada** [comment]
Also I was thinking maybe we could do an `see_args` func that would open a floating window with `<leader>;` or something like that. Maybe it should even be "scroll-able". 
(so it is finally possible to see everything available to the Class in question, avoiding the `...` trunc style. This is in regards to Classes with a high count of args like the ones from FLuidCorpusManipulation - as  an example)

**Comment by salkin-mada** [comment]
> @salkin-mada CPU usage is now on-par with ScIDE (at least on my system).
> I've used this snippet for testing `Pbind(\degree, Pseq((0..9), inf), \dur, 1/512).trace.play;`. I have thought about some more optimizations as well, but I think that will have to wait until I port `postwindow.vim` completely to lua :)
> 
very nice! great work. i can post rapidly now without killing my cpu. let me know in the tele chat what you optimization ideas for the full .lua postwindow would be? interested :+1:

**Comment by davidgranstrom** [comment]
> Also I was thinking maybe we could do an `see_args` func that would open a floating window with `<leader>;` or something like that. Maybe it should even be "scroll-able".
> (so it is finally possible to see everything available to the Class in question, avoiding the `...` trunc style. This is in regards to Classes with a high count of args like the ones from FLuidCorpusManipulation - as an example)

I was planning on working on this next, I've started some work already on this [branch](https://github.com/davidgranstrom/scnvim/tree/topic/arghints-lua). The idea is to deliver all needed sclang introspection to lua at startup to avoid runtime queries to sclang. I will rebase that branch once this is merged (haven't had a chance to test on windows yet..)

With that said, you could probably do something like this at the moment if you really want to have that feature immediatley :) 

```lua
local scnvim = require'scnvim'

function get_args(method)
  if scnvim.is_running() then
    local cmd = string.format('Help.methodArgs(\\"%s\\")', method);
    scnvim.eval(cmd, function(result)
      -- trim away the class and method name
      local args = result:gsub('^.*%(', ''):gsub('%)', '')
      print(args) -- display in a floating window
    end)
  end
end

-- call from some mapping
get_args('SinOsc.ar')
```

(note that the code requires this branch to work)

**Comment by salkin-mada** [comment]
nice!

**Comment by ranjithshegde** [comment]
> I have a local branch running here which supports `:SCNvimTags` creating lua style snippets and which offers `scnvim` support of `snippets.nvim` in addition til `UltiSnips`

Is this branch accessible on your github? Would really appreciate having a look, I would love for snippets.nvim to recognize my scnvim tags

**Comment by salkin-mada** [comment]
Yes it's at [https://github.com/salkin-mada/scnvim/tree/salkin-dev](https://github.com/salkin-mada/scnvim/tree/salkin-dev)

with packer.nvim thats:
```
        use {
            'salkin-mada/scnvim',
            branch = 'salkin-dev',
        }
```

then in scnvim running `:SCNvimTags` wil generate a lua snippet file for you.

i then combine them with my own supercollider snippets like so:
```
for k,v in pairs(require'auto_generated_scnvim_snippets') do snippets.supercollider[k] = v end
```

it works fine for my usage at the moment.

pleas note that not all the snippets in `auto_generated_scnvim_snippets.lua` works.
there is some minor issues on some methods.

scrn-2021-03-19-15-44-50
scrn-2021-03-19-15-44-50

also next step would be to add some user config posibilities in scnvim like we do with the help-file system (pandoc, html2text)
some vim.g.sncvim_snippet_system = 'snippets.nvim' or 'ultisnips'.

for now in my branch - just hardcore changed ultisnips with snippets.nvim

but making this chooseable and make a PR to upstream is something i def should get around to at some point.

**Comment by ranjithshegde** [comment]
> ```
> for k,v in pairs(require'auto_generated_scnvim_snippets') do snippets.supercollider[k] = v end
> ```
> 
> it works fine for my usage at the moment.
> 
Thank you. Somehow does not work for me. I am not doing this last step as I am not using any custom snippets these days.
Are you on completion-nvim?

> also next step would be to add some user config posibilities in scnvim like we do with the help-file system (pandoc, html2text)
> some vim.g.sncvim_snippet_system = 'snippets.nvim' or 'ultisnips'.

> but making this chooseable and make a PR to upstream is something i def should get around to at some point.

That would be a great idea!

**Comment by salkin-mada** [comment]
@ranjithshegde I used `completion-nvim` up until last Thursday (have been using it since i moved to nvim nightly and migrated to lua, x months ago). Now i use `nvim-compe`.

I wonder why it does not work in your end. Is the file `auto_generated_scnvim_snippets.lua` being generated after `:SCNvimTags`, can you locate the file in your system? How to you tell `snippets.nvim` about this file?
maybe there is some problem with you `nvim` snippets configuration.

Will start to work on a PR then.

**Comment by ranjithshegde** [comment]
@salkin-mada It does generate the auto_generated_scnvim_snippets.lua which I put in my package_path

snippets.nvim just does not find them. Cant see why

**Comment by salkin-mada** [comment]
@ranjithshegde after adding the file to the package path you will have to require the table within.
depending on how you set up `snippets.nvim` (how you are actually setting/loading/requiring snippets for each language)

* minimum example:
```lua
local S = require'snippets'
local snippets = S.snippets
package.path = package.path .. ";/home/salkin/kode/scnvim-fork/scnvim/scnvim-data/auto_generated_scnvim_snippets.lua"
snippets = {
    _global = {
        uname = function() return vim.loop.os_uname().sysname end;
        date = "${=os.date('%d-%m-%Y')}";
        time = "${=os.date('%H:%M:%S')}";
        line = [[${=tostring(vim.api.nvim_win_get_cursor(0)[1])}]];
        randcolor = function()
            return format("#%06X", math.floor(math.random() * 0xFFFFFF))
        end;
        -- etc. global snippets. (works in all buffers)
        };
        sh = {
            -- maybe some bash/zsh snippets?
        };
        rust = {
            -- some rust snippets
        };
        lua = { };
        --etc etc etc.
        -- the lang in question here
       supercollider = require'auto_generated_scnvim_snippets'; -- autogenerated snippets from scnvim

```
this should be enough to use the scnvim snippets

The reason that i am using this:
```lua
-- after snippets = {... ... .. supercollider = ... etc };
for k,v in pairs(require'auto_generated_scnvim_snippets') do snippets.supercollider[k] = v end
S.snippets = snippets
``` 
is that i am combining the autogenerated scnvim snippets with my own snippets which is already "loaded" into the table of the `S.snippets.supercollider`.
Therefor the above `k,v in pairs...`

and then in my case the supercollider part in the snippets table looks like
```
snippets = {
     supercollider = require'my-own-supercollider-snippets'; -- snippets from a repository / lua dir
```

**Comment by salkin-mada** [comment]
`nvim-compe` just works better overall in my experience. First notable difference on my system at least was its handling of paths.
It just works. I seems to have a better hmm context sensibility. nvim-completion tends to overflow my completion list with `lsp` stuff and `tags`. both things that i want in my list. but maybe not on the top when i am actually completing a path (sub-directory/or file after i triggered the first `path` entry in the completion menu/list)

**Comment by salkin-mada** [comment]
@ranjithshegde #139
when merged you can use `davidgranstrom/scnvim` again.

**Comment by ranjithshegde** [comment]
> `nvim-compe` just works better overall in my experience. First notable difference on my system at least was its handling of paths.
> It just works. It seems to have a better ..hmm.. context sensibility. nvim-completion tends to overflow my completion list with `lsp` stuff and `tags`. both things that i want in my list. but maybe not on the top when i am actually completing a path (sub-directory/or file after i triggered the first `path` entry in the completion menu/list)

I will try it. Just got used to having to manually switch between sources in completion.nvim. like the oldschool omni! 

Btw, compared to UltiSnips, does snippets.nvim also place you in insert mode where you need to manually remove the placeholder and type the values instead of placing you in select/visual-replace mode

This issue
Snippets

**Pull request merged**
