### PR TITLE
Sclang command line options

### PR DESCRIPTION
**Pull request by john-d-murphy**

### CODE REVIEW

**Comment by john-d-murphy** [comment]
I needed to add the ability to set the sclang configuration file for some code I was working on, so I figured it would be helpful if it were possible to add the other relevant command-line options as well. This pull request should cover those, and I'm happy to make any changes you'd like so it folds into the main branch nicely.

Thanks!

**Comment by davidgranstrom** [comment]
@john-d-murphy Thanks, this looks really useful! The PR looks very good also. After reviewing this I'm starting to think that an array could be more suitable for this purpose in order to introduce less option variables. We could instead use `g:scnvim_sclang_options = []` which should be empty by default, then users could easily insert arguments as they see fit. A note could be added in the documentation that `-i` and `-d` options are automatically set by `scnvim` and should not be used.

*autoload/sclang.vim*
```vim
let job.cmd = job.cmd + get(g:, 'scnvim_sclang_options', [])
```

*init.vim*
```vim
" use a different UDP port for sclang
let g:scnvim_sclang_options = ['-u', 9999]
```

**Comment by john-d-murphy** [comment]
That definitely can work. My concern would be that some of the command line options (notably -a, -v, -i, and -D) would cause the slang process to behave incorrectly and could be difficult for the enduser to debug, hence the explicit definition of options. 

Perhaps the list could be pared down - maybe limit the available set to just -u and -l ?

**Comment by davidgranstrom** [comment]
Normally I would agree with your point about usage, however since this could be considered an "advanced" configuration option (I don't think there is a way to configure this in the IDE even, but maybe I'm mistaken?) that it is better to leave the API open, i.e. just pass in an array of options as above to cover all current and possibly future cases of sclang command line options. We could include examples in the docs for the most common cases like setting a custom UDP port for sclang, or maybe sourcing a different library config?

**Comment by john-d-murphy** [comment]
I just checked the IDE and it's not readily apparent that these are options that can be set in the GUI. 
While I'm not sure I agree with the conclusion, I am happy to make the suggested change and put in documentation with examples.  

I'll make the update after I'm done with work for the day, so you should see an update to the pull request tomorrow morning your time.

**Comment by davidgranstrom** [comment]
Thanks, that sounds great! Regarding the documentation there is a similar option (`g:scnvim_scdoc_render_args`) documented at `:h scnvim-help-system` under "Customization" that might be helpful.

**Comment by john-d-murphy** [comment]
Modified the code to a one-liner and updated the documentation.

```
let job.cmd = [prg, '-i', 'scnvim', '-d', rundir] + get(g:, 'scnvim_sclang_options', [])
```

Tested in my local environment and it works as you'd expect. 
I still think this may be potentially confusing/dangerous for users, so please let me know if this causes an uptick in support and I'll modify it to use individual configurations similar to the original pull request.

Thanks!

**Comment by davidgranstrom** [comment]
@john-d-murphy Thanks, looks good!

**Pull request merged**
