### PR TITLE
Be able to print function signature on demand

### LINKED ISSUE #113: [FR]: Add command for manually echoing args
I would love a feature that would let you manually (re)echo args from a method. as it is now, `scnvim#util#echo_args()` is called by an autocmd, but at least I cannot retrigger this manually using `:call scnvim#util#echo_args()` (or maybe every time the cursor passes over a method?)

### PR DESCRIPTION
**Pull request by davidgranstrom**
Closes #113

### CODE REVIEW

**Comment by davidgranstrom** [comment]
TODO: Add default mapping to documentation.

**Comment by madskjeldgaard** [comment]
It works as expected here

**Comment by madskjeldgaard** [comment]
Oh and I see there is a mapping for it. That works as well. Thanks so much! This is perfect IMO.

**Comment by davidgranstrom** [comment]
@madskjeldgaard Thanks for your feedback! I renamed the default mapping (in case you've remapped it already) and added documentation. Will merge this now.

**Pull request merged**
