### PR TITLE
fix percent symbol in status line

### PR DESCRIPTION
**Pull request by sadguitarius**
Hi @davidgranstrom, can you check if this works for you? I think my brain is missing the part that allows me to understand git. Let me know if we're good here and I can go ahead with the other commit. Thanks!

### CODE REVIEW

**Comment by davidgranstrom** [comment]
@sadguitarius Thanks, commit looks fine! I just need to try it out, will get back to you soon.

**Comment by davidgranstrom** [comment]
Finally got a chance to try this it. Unfortunately this change prints double percentage signs on macOS (see attached image). I'm guessing this could be a Windows specific string escaping issue? What does `"%\\%".format(100);` print if on your end (from the IDE)? 

One solution might be to change the server format string according to the host platform, but would be good to pinpoint where the string escaping fails.

Screenshot 2022-03-29 at 09 49 09

**Comment by sadguitarius** [comment]
Hi David, I did a little poking around and I think the issue might actually be with lualine and it's use of % sign to designate substitutions. Apparently lualine needs to double up the symbol in order to un-escape it. I just changed my statusline function to include

```
local stat = vim.fn["scnvim#statusline#server_status"]()
stat = stat:gsub("%%", "%%%%")
```

and the % sign is printed correctly. Might be worth adding a note about this in the wiki since others are likely to bump into this when trying to move configs from vimscript to lua. Sorry for the confusion!

**Comment by davidgranstrom** [comment]
@sadguitarius Thanks for looking into this, that makes sense.

You are welcome to add a note about this in the wiki, its open for editing!

**Pull request closed without merging**
